### ISSUE TITLE
playdead

### ISSUE THREAD

**Issue by pawel37** [marcinwrobel1986/PortaPack-Havoc-HackRF#1]
u can u fix play dead mate

**Comment by marcinwrobel1986** [comment]
Hi, 
here is the thread from authors repo.
https://github.com/furrtek/portapack-havoc/issues/261
I just compiled binary from source and put them together, write a script, so the flashing is painless for the new users.

**Comment by pawel37** [comment]
so u can fix play dead on ur bin file because u have the icons in the menu

**Comment by marcinwrobel1986** [comment]
I checked issues you opened and found this one:
"hello i found a havoc.bin with icons in the menu not text but i cant find it again can any help"
There were an update to the UI and in the latest version there are icons and menu looks different.
Take a look in original repo:
https://github.com/furrtek/portapack-havoc
The comment added to a commit is: "UI Redesign for Portapack-Havoc (#268)"
